# Generated by Django 4.1 on 2022-12-12 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoUntukSearchFlutter',
            fields=[
                ('nama', models.CharField(max_length=128)),
                ('kota', models.CharField(max_length=64)),
                ('provinsi', models.CharField(max_length=64)),
                ('lokasi', models.CharField(max_length=128)),
                ('deskripsi', models.TextField()),
                ('range_harga', models.CharField(choices=[('mahal', 'Mahal'), ('sedang', 'Sedang'), ('murah', 'Murah')], max_length=6)),
                ('buka', models.BooleanField(default=True)),
                ('kondisi', models.CharField(choices=[('ramai', 'Ramai'), ('sedang', 'Sedang'), ('sepi', 'Sepi')], max_length=6)),
                ('pemilik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
