# Generated by Django 4.1 on 2022-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0002_tokountuksearchflutter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokountuksearchflutter",
            name="pemilik",
        ),
        migrations.AddField(
            model_name="tokountuksearchflutter",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
