# Generated by Django 4.1 on 2022-10-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pesan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesan", models.CharField(max_length=256)),
                (
                    "pengirim",
                    models.CharField(
                        choices=[("pengirim", "Pengirim"), ("user", "User")],
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
