# Generated by Django 4.1 on 2022-10-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
