# Generated by Django 4.1 on 2022-10-16 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "harga",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("deskripsi", models.TextField()),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("makanan", "Makanan"),
                            ("minuman", "Minuman"),
                            ("pakaian", "Pakaian"),
                            ("alat_tulis", "Alat Tulis"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JadwalOperasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hari", models.CharField(max_length=8)),
                (
                    "jam_buka",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ]
                    ),
                ),
                (
                    "jam_tutup",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ]
                    ),
                ),
            ],
        ),
    ]
