# Generated by Django 4.1 on 2022-10-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detail", "0001_initial"),
        ("katalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jadwaloperasi",
            name="toko",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="katalog.toko"
            ),
        ),
        migrations.AddField(
            model_name="barang",
            name="toko",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="katalog.toko"
            ),
        ),
    ]
