# Generated by Django 4.1 on 2022-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detail", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barang",
            name="nama",
            field=models.CharField(default="Barang", max_length=128),
            preserve_default=False,
        ),
    ]
