name: Test and Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.10.6"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect static files
        run: python manage.py collectstatic

      - name: Test and generate report
        run: |
          pip install coverage
          coverage run --source='.' manage.py test

      - name: Show coverage report
        run: coverage report
